package default_package;


import java.awt.Color;
import javax.swing.DefaultListModel;

public class frmShowPrize extends javax.swing.JFrame {
	static frmMain frmMain;
	DefaultListModel model;
	// BasePersonnel[] tempPersonnels = frmMain.PersonnelManager.Personnels;

	/**
	 * Creates new form frmShowPrize
	 */
	public frmShowPrize(frmMain frmMain) {
		this.frmMain = frmMain;
		model = new DefaultListModel();
		initComponents();
		getContentPane().setBackground(frmMain.getContentPane().getBackground());
		getContentPane().setForeground(frmMain.getContentPane().getForeground());
		getContentPane().setForeground(Color.RED);
		pnlPersonnelPrize.setOpaque(false);
		lstPersonnel2.setModel(model);
		frmMain.PersonnelManager.SortofSalary(frmMain.PersonnelManager.Personnels);
		for (int i = 0; i < frmMain.PersonnelManager.Personnels.length; i++) {
			model.addElement(frmMain.PersonnelManager.Personnels[i].getName() + " "
					+ frmMain.PersonnelManager.Personnels[i].getSurname());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		lblTitle = new javax.swing.JLabel();
		pnlPersonnelPrize = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		lstPersonnel2 = new javax.swing.JList<>();
		lblNameSurname = new javax.swing.JLabel();
		lblSalary = new javax.swing.JLabel();
		lblPosition = new javax.swing.JLabel();
		lblSalesAmount = new javax.swing.JLabel();
		txtSalesAmount = new javax.swing.JTextField();
		lblCalculatedPrize = new javax.swing.JLabel();
		btnShowPrize = new javax.swing.JButton();
		btnSalesAmount = new javax.swing.JButton();
		lblNameSurname2 = new javax.swing.JLabel();
		lblSalary2 = new javax.swing.JLabel();
		lblPosition2 = new javax.swing.JLabel();
		lblCalculatedPrize2 = new javax.swing.JLabel();
		btnBack = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Prize of Personnels");
		setResizable(false);

		lblTitle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblTitle.setText("Personnel Prize");

		lstPersonnel2.setModel(new javax.swing.AbstractListModel<String>() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

			public int getSize() {
				return strings.length;
			}

			public String getElementAt(int i) {
				return strings[i];
			}
		});
		lstPersonnel2.setSelectionBackground(new Color(214, 217, 223));
		lstPersonnel2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				lstPersonnel2MouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(lstPersonnel2);

		lblNameSurname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblNameSurname.setText("Name Surname :");

		lblSalary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblSalary.setText("Salary :");
		lblSalary.setToolTipText("");
		lblSalary.setAutoscrolls(true);

		lblPosition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblPosition.setText("Position :");

		lblSalesAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblSalesAmount.setText("Shift Hours :");

		txtSalesAmount.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtSalesAmountActionPerformed(evt);
			}
		});

		lblCalculatedPrize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblCalculatedPrize.setText("Calculated Prize :");

		btnShowPrize.setText("Show Personnel Prize");
		btnShowPrize.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnShowPrizeActionPerformed(evt);
			}
		});

		btnSalesAmount.setText("Set Shifts Amount");
		btnSalesAmount.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSalesAmountActionPerformed(evt);
			}
		});

		lblNameSurname2.setBackground(new Color(255, 255, 255));
		lblNameSurname2.setText("The Name and Surname of the Personnel");
		lblNameSurname2.setOpaque(true);

		lblSalary2.setBackground(new Color(255, 255, 255));
		lblSalary2.setText("The Salary of the Personnel");
		lblSalary2.setAutoscrolls(true);
		lblSalary2.setOpaque(true);

		lblPosition2.setBackground(new Color(255, 255, 255));
		lblPosition2.setText("The Position of the Personnel");
		lblPosition2.setOpaque(true);

		lblCalculatedPrize2.setBackground(new Color(255, 255, 255));
		lblCalculatedPrize2.setOpaque(true);

		javax.swing.GroupLayout pnlPersonnelPrizeLayout = new javax.swing.GroupLayout(pnlPersonnelPrize);
		pnlPersonnelPrize.setLayout(pnlPersonnelPrizeLayout);
		pnlPersonnelPrizeLayout.setHorizontalGroup(pnlPersonnelPrizeLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlPersonnelPrizeLayout.createSequentialGroup().addGap(51, 51, 51)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
						.addGroup(pnlPersonnelPrizeLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(pnlPersonnelPrizeLayout.createSequentialGroup()
										.addComponent(lblSalesAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 134,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(txtSalesAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 376,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(pnlPersonnelPrizeLayout.createSequentialGroup()
										.addComponent(lblPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 134,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(lblPosition2, javax.swing.GroupLayout.PREFERRED_SIZE, 376,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(pnlPersonnelPrizeLayout.createSequentialGroup()
										.addComponent(lblSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 130,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(lblSalary2, javax.swing.GroupLayout.PREFERRED_SIZE, 376,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(pnlPersonnelPrizeLayout.createSequentialGroup()
										.addComponent(lblNameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 134,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(lblNameSurname2, javax.swing.GroupLayout.PREFERRED_SIZE, 376,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(pnlPersonnelPrizeLayout.createSequentialGroup()
										.addComponent(lblCalculatedPrize, javax.swing.GroupLayout.PREFERRED_SIZE, 134,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(pnlPersonnelPrizeLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(lblCalculatedPrize2,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 376,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														pnlPersonnelPrizeLayout.createSequentialGroup()
																.addComponent(btnSalesAmount,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 168,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(btnShowPrize,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 158,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))))
						.addGap(39, 39, 39)));
		pnlPersonnelPrizeLayout.setVerticalGroup(pnlPersonnelPrizeLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlPersonnelPrizeLayout.createSequentialGroup().addGap(21, 21, 21)
						.addGroup(pnlPersonnelPrizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(pnlPersonnelPrizeLayout.createSequentialGroup()
										.addGroup(pnlPersonnelPrizeLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblNameSurname, javax.swing.GroupLayout.PREFERRED_SIZE,
														50, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(lblNameSurname2, javax.swing.GroupLayout.PREFERRED_SIZE,
														50, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(pnlPersonnelPrizeLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblSalary).addComponent(lblSalary2,
														javax.swing.GroupLayout.PREFERRED_SIZE, 50,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(pnlPersonnelPrizeLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(lblPosition2, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(11, 11, 11)
										.addGroup(pnlPersonnelPrizeLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblSalesAmount, javax.swing.GroupLayout.PREFERRED_SIZE,
														50, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(txtSalesAmount, javax.swing.GroupLayout.PREFERRED_SIZE,
														50, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(pnlPersonnelPrizeLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(lblCalculatedPrize,
														javax.swing.GroupLayout.PREFERRED_SIZE, 50,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(lblCalculatedPrize2,
														javax.swing.GroupLayout.PREFERRED_SIZE, 50,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100,
												Short.MAX_VALUE)
										.addGroup(pnlPersonnelPrizeLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btnShowPrize, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(btnSalesAmount, javax.swing.GroupLayout.PREFERRED_SIZE,
														40, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap()))));

		btnBack.setText("Back Main Menu");
		btnBack.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBackActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 130,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup()
						.addComponent(pnlPersonnelPrize, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 46, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(pnlPersonnelPrize, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(96, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
		// TODO add your handling code here:
		frmMain.setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_btnBackActionPerformed

	private void lstPersonnel2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lstPersonnel2MouseClicked
		// TODO add your handling code here:
		int index = lstPersonnel2.getSelectedIndex();

		lblNameSurname2.setText(frmMain.PersonnelManager.Personnels[index].getName() + " "
				+ frmMain.PersonnelManager.Personnels[index].getSurname());
		lblSalary2.setText(Integer.toString(frmMain.PersonnelManager.Personnels[index].getSalary()));
		lblPosition2.setText(frmMain.PersonnelManager.Personnels[index].getPosition());
		txtSalesAmount.setText(Double.toString(frmMain.PersonnelManager.Personnels[index].getPrimAmount()));
		lblCalculatedPrize2.setText(" ");
	}// GEN-LAST:event_lstPersonnel2MouseClicked

	private void btnSalesAmountActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalesAmountActionPerformed
		// TODO add your handling code here:
		double prize = Double.parseDouble(txtSalesAmount.getText());
		int index = lstPersonnel2.getSelectedIndex();
		frmMain.PersonnelManager.Personnels[index].setPrimAmount(prize);
		// frmMain.PersonnelManager.Personnels[tempPersonnels[index].getId()].setPrimAmount(prize);
	}// GEN-LAST:event_btnSalesAmountActionPerformed

	private void btnShowPrizeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnShowPrizeActionPerformed
		// TODO add your handling code here:
		int index = lstPersonnel2.getSelectedIndex();
		double prize = frmMain.PersonnelManager.Personnels[index].getPrimAmount();
		lblCalculatedPrize2.setText(Double.toString(frmMain.PersonnelManager.Personnels[index].primCalculator(prize)));
	}// GEN-LAST:event_btnShowPrizeActionPerformed

	private void txtSalesAmountActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtSalesAmountActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtSalesAmountActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(frmShowPrize.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(frmShowPrize.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(frmShowPrize.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(frmShowPrize.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new frmShowPrize(frmMain).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnBack;
	private javax.swing.JButton btnSalesAmount;
	private javax.swing.JButton btnShowPrize;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblCalculatedPrize;
	private javax.swing.JLabel lblCalculatedPrize2;
	private javax.swing.JLabel lblNameSurname;
	private javax.swing.JLabel lblNameSurname2;
	private javax.swing.JLabel lblPosition;
	private javax.swing.JLabel lblPosition2;
	private javax.swing.JLabel lblSalary;
	private javax.swing.JLabel lblSalary2;
	private javax.swing.JLabel lblSalesAmount;
	private javax.swing.JLabel lblTitle;
	private javax.swing.JList<String> lstPersonnel2;
	private javax.swing.JPanel pnlPersonnelPrize;
	private javax.swing.JTextField txtSalesAmount;
	// End of variables declaration//GEN-END:variables
}